/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ca.ewert.notarytool.gradle

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class NotarytoolGradlePlugin : Plugin<Project> {
  override fun apply(project: Project) {
    // Register a task
    project.tasks.register("greetingTask") { task ->
      task.group = "notarytool"
      task.doLast {
        println("Hello from plugin 'ca.ewert.notarytool.gradle.greeting'")
      }
    }
  }
}
