/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ca.ewert.notarytool.gradle

import assertk.assertThat
import assertk.assertions.isEqualTo
import assertk.assertions.isNotNull
import org.gradle.api.Task
import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test

/**
 * A simple unit test for the 'ca.ewert.notarytool.gradle.greeting' plugin.
 */
class NotarytoolGradlePluginTest {

  @Test
  fun pluginRegistersTask() {
    // Create a test project and apply the plugin
    val project = ProjectBuilder.builder().build()
    project.plugins.apply("ca.ewert.notarytool.gradle")
    println("Hello Test")

    // Verify the result
//    assertNotNull(project.tasks.findByName("greetingTask"))
    val greetingTask: Task? = project.tasks.findByName("greetingTask")
    assertThat(greetingTask).isNotNull()
    assertThat(greetingTask?.name).isEqualTo("greetingTask")
    assertThat(greetingTask?.group).isEqualTo("notarytool")
    assertThat(greetingTask?.description).isNotNull()
  }
}
