/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ca.ewert.notarytool.gradle

import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir
import java.io.File
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'ca.ewert.notarytool.gradle.greeting' plugin.
 */
class NotarytoolGradlePluginFunctionalTest {

  @field:TempDir
  lateinit var projectDir: File

  private val buildFile by lazy { projectDir.resolve("build.gradle") }
  private val settingsFile by lazy { projectDir.resolve("settings.gradle") }

  @Test
  fun canRunTask() {
    // Set up the test build
    settingsFile.writeText("")
    buildFile.writeText(
      """
        plugins {
            id('ca.ewert.notarytool.gradle')
        }
      """.trimIndent(),
    )

    println("Build File: ${buildFile.absolutePath}")

    // Run the build
    val runner = GradleRunner.create()
    runner.forwardOutput()
    runner.withPluginClasspath()
    runner.withArguments("greeting")
    runner.withProjectDir(projectDir)
    val result = runner.build()

    // Verify the result
    assertTrue(result.output.contains("Hello from plugin 'ca.ewert.notarytool.gradle.greeting'"))
  }
}
